### PR TITLE
Quality of life changes.

### PR DESCRIPTION
**Pull request by veganlies2me**
Quality of life changes that give the user more freedom. Ability to change the background color and to turn off the orange box.
Here is a demonstration video. The model is the cyborg protagonist from X-Men: The Ravages of Apocalypse.

https://github.com/user-attachments/assets/77e4f711-3259-4b3d-81da-26997c6860ad

### CODE REVIEW

**Review by TheEnbyWitch — APPROVED** [review]

**Comment by veganlies2me** [comment]
Not working on Linux?

**Comment by TheEnbyWitch** [comment]
> Not working on Linux?

That's an issue with the GitHub Action workflows. I had the wrong version of the premake setup set, and github deprecated the old upload-artifact versions.

I'm working on fixing that right now though.

**Comment by TheEnbyWitch** [comment]
I don't know how to force a rerun with the latest GitHub Action Workflows, could you update the main branch on your end?

**Comment by veganlies2me** [comment]
Did it update?

**Comment by TheEnbyWitch** [comment]
Apologies on not getting back sooner! The build ran successfully now, and it looks safe to merge.

**Review by TheEnbyWitch — APPROVED** [review]

**Pull request merged**
